#pragma once

/* PMW3360 Trackball (обязательно до инклюда quantum.h) */
#define PMW3360_CS_PIN GP14
#define PMW3360_DPI 1600

/* SPI для RP2040 */
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP18
#define SPI_MISO_PIN GP20
#define SPI_MOSI_PIN GP19

/* Split & Pointing Device */
#define MASTER_RIGHT
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_ROTATION_90
#define SERIAL_USART_TX_PIN GP1
#define SERIAL_USART_FULL_DUPLEX

/* RP2040 Bootloader & EEPROM */
#define RP2040_FLASH_WEAR_LEVELING_SIZE 16384
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
