#pragma once

/* Split & Handedness */
#define MASTER_RIGHT
#define SERIAL_USART_TX_PIN GP1
#define SERIAL_USART_FULL_DUPLEX

/* SPI & PMW3360 Trackball */
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP18
#define SPI_MISO_PIN GP20
#define SPI_MOSI_PIN GP19
#define POINTING_DEVICE_CS_PIN GP14
#define PMW3360_DPI 1600

/* RP2040 Bootloader */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17

/* EEPROM */
#define RP2040_FLASH_WEAR_LEVELING_SIZE 16384
