VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
QMK_SETTINGS = yes
COMBO_ENABLE = yes
ONE_SHOT_ENABLE = yes
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
VIALRGB_ENABLE = no
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
SPLIT_KEYBOARD = yes
MOUSE_ENABLE = yes
EEPROM_DRIVER = vendor
BOOTLOADER = rp2040

# FIX: Явно указываем драйвер, чтобы пройти валидацию QMK (даже при отключенном RGB)
RGB_MATRIX_DRIVER = ws2812
