# Core & Vial
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
QMK_SETTINGS = no

# Features (отключено для экономии flash и избежания конфликтов)
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = no
ONE_SHOT_ENABLE = no
MOUSE_ENABLE = yes

# RGB (полностью отключено)
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
VIALRGB_ENABLE = no

# Pointing Device
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360

# Split & RP2040
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
EEPROM_DRIVER = vendor
BOARD = GENERIC_PROMICRO_RP2040
BOOTLOADER = rp2040
