BOOTLOADER = rp2040
BOARD = GENERIC_PROMICRO_RP2040

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
EEPROM_DRIVER = vendor

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
MOUSE_ENABLE = yes

RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
VIALRGB_ENABLE = no
